### ISSUE TITLE
TIQR isn't "Phishsafe"

### ISSUE THREAD

**Issue by cyberphone** [SURFnet/tiqr-client-android#39]
Systems like TIQR are quite popular in Europe.
Unfortunately they share a common weakness, they are susceptible to phishing.

AFAICT, you need a Secure QR in order to get away from that problem.

I have suggested that an upgraded version of WebNFC could function as "A Better QR" which would increase both convenience and security.

The same system could also stop the onslaught of QR-based payment systems.

Is that something SURFnet could be interested in?

https://github.com/w3c/web-nfc/issues/101#issuecomment-304683141

**Comment by joostd** [comment]
Yes, that sounds interesting. 

Phishing protection in tiqr is now restricted to a user notification where the authentication request is originating from, but if the user ignores this notification and/or doesn't verify server certificates, he/she is vulnerable.

Until now we haven't considered using NFC due to the lack of support on iOS, but that seems to be changing: https://developer.apple.com/documentation/corenfc 

We will have a look at the web-nfc specs. I don't immediately see how using NFC is more secure than scanning a QR code though.

**Comment by cyberphone** [comment]
@joostd Good news about Apple, I didn't know that.

The security difference between QR and WebNFC for TIQR and similar with respect to phishing is that WebNFC can provide a _trustworthy_ Web page security context (URL etc.) as well which would make phishing attacks known by the phone or by the authentication server.

https://github.com/w3c/web-nfc/issues/128
